from .check_settings_widget import CheckSettingsWidget
from .check_parameterEditor_widget import CheckParameterEditorWidget
from .checks_widget import ChecksWidget
from .check_restrictionsEditor_widget import CheckRestrictionsEditorWidget
